# Generated by Django 3.0.6 on 2020-05-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_menu_dinner_platter_menu_pasta_menu_salad_menu_sub_menu_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
