# Generated by Django 3.0.6 on 2020-05-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_all_orders_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_orders',
            old_name='price',
            new_name='item_price',
        ),
    ]
