# Generated by Django 3.0.6 on 2020-05-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200512_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_orders',
            new_name='total_order',
        ),
    ]
